### ISSUE TITLE
Bad regex testing for LGTM message

### ISSUE THREAD

**Issue by sedouard** [felixrieseberg/peer-review-bot#1]
This regex `(LGTM)|(Looks good to me!)|w+?` will match `w`'s followed by a space in the message. See:

<img width="1836" alt="screen shot 2015-08-27 at 1 34 30 pm" src="https://cloud.githubusercontent.com/assets/3053263/9530975/55ab8e5e-4cc0-11e5-9317-94f13a2d9e98.png">

This causes the crazyness seen here:

https://github.com/CatalystCode/case-studies/pull/63

**Comment by felixrieseberg** [comment]
Uuuuuuuuuughhhhh. Thank you so much :heart:
